shoppingcart/shoppingcart/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'shoppingcart.views.home', name='home'),

    url(r'^store/', include('store.urls', namespace='store')),

    url(r'^admin/', include(admin.site.urls)),

    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

shoppingcart/store/urls.py
from django.conf.urls import url
from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.home, name='store_home'),
    url(r'^profile/$', views.profile, name='user_profile')
]

shoppingcart/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Product(models.Model):
    title = models.CharField(null=False ,max_length=50)
    description = models.TextField(default='')
    price = models.IntegerField(default=0)
    # on_sale
    # sale_discount

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    avatar = models.TextField(max_length=500, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

shoppingcart/store/views.py
from django.shortcuts import render
from django.http import HttpResponse

# decorators
from django.contrib.auth.decorators import login_required

from .models import Product

# Create your views here.
def home(request):
    products = Product.objects.all()
    context = {
        'product_list': products,
        'user': request.user
    }
    return render(request, 'store/home.html', context)

@login_required(login_url='/store/')
def profile(request):
    logged = None
    if request.user.is_authenticated():
        logged = request.user

    return render(request, 'store/profile.html', {'user': logged})

shoppingcart/store/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
    <head>
        <title>
            {% block page_title %}
                
            {% endblock page_title %}
        </title>

        <link rel="stylesheet" href="{% static "store/css/styles.css" %}">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-light bg-faded">
            <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            &#9776;
            </button>
            <div class="collapse navbar-toggleable-xs" id="navbarCollapse">
                <a class="navbar-brand" href="#">Store</a>
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Featured</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sale</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        {% if user and not user.is_anonymous %}
                            <a class="nav-link" href="{% url 'store:user_profile' %}">Hello {{ user.get_full_name|default:user.username }}!</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>

        <div id="wrapper" class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="card">
                        <div class="card-block">
                            <form action="#">
                                <input
                                    type="text"
                                    class="form-control"
                                    placeholder="Search">
                            </form>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Cat 1</li>
                            <li class="list-group-item">Cat 2</li>
                            <li class="list-group-item">Cat 3</li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-9">
                    {% block page_content %}
                        
                    {% endblock page_content %}
                </div>
            </div>
        </div>

        <footer>
            I am the footer &copy; 2016
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
    </body>
</html>

shoppingcart/store/templates/store/home.html
{% extends "base.html" %}
{% block page_title %}
    Store Home
{% endblock page_title %}

{% block page_content %}
    <div class="container">
        <div class="row">
            <h2>Featured Items</h2>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <h2>Items on Sale</h2>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <h2>Recently Added</h2>
            <div class="card-deck-wrapper">
                <div class="card-deck">
                {% for product in product_list %}
                    <div class="card card-block">
                        <h4 class="card-title">{{ product.title }}</h4>
                        <p class="card-text">
                            {{ product.description }}
                        </p>
                        <a href="#" class="card-link">View</a>
                        <a href="#" class="card-link">Add to Cart</a>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

shoppingcart/store/templates/store/profile.html
{% extends "base.html" %}
{% block page_title %}
    Profile Page
{% endblock page_title %}

{% block page_content %}
    <div class="container">
        <div class="row">
            <h2>{{ user.get_username }}</h2>
            <img
                src="{{ user.profile.avatar }}"
                alt="{{ user.get_username }}"
                class="img-circle">
        </div>
    </div>
{% endblock page_content %}